# Clone your repository (if you haven't already)
git clone https://github.com/YOUR_USERNAME/YOUR_REPOSITORY.git
cd YOUR_REPOSITORY

# Create the workflows directory
mkdir -p .github/workflows

# Create the workflow file
cat > .github/workflows/daily-commit.yml << 'EOF'
name: Daily Auto Commit

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Step with email 23f2004672@ds.study.iitm.ac.in
      run: |
        echo "Last auto-commit: $(date)" > last_commit.txt
        
    - name: Commit changes
      run: |
        git config --local user.email "23f2004672@ds.study.iitm.ac.in"
        git config --local user.name "GitHub Action"
        git add last_commit.txt
        git commit -m "Daily auto-commit [23f2004672@ds.study.iitm.ac.in] - $(date)" || exit 0
        
    - name: Push changes
      run: |
        git push
EOF

# Add, commit, and push the file
git add .github/workflows/daily-commit.yml
git commit -m "Add daily auto-commit workflow"
git push
