name: Email Test Action

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: 23f2004672@ds.study.iitm.ac.in
        run: echo "This step uses my email in the name."
